baseURL: "https://maartengoos.com" 
title: Maarten Goos
paginate: 20
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
taxonomies:
    tag: tags
menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Working papers
          url: /research/
          weight: 2
        - name: Publications
          url: /publications/
          weight: 3
        - name: Courses
          url: /courses/
          weight: 4        
params:
    description: "homepage of Maarten Goos"
    author: Maarten Goos
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Maarten Goos
          subtitle: "Welcome to my homepage! I am a labor economist. My research and courses focus on labor problems, technological change, industrial relations, what unions do, monopsony, and inequality."
          imageUrl: "/picture.jpg"
          imageWidth: 320
          imageHeight: 320
          imageTitle: Maarten Goos
          buttons:
            - name: Working papers
              url: /research/
            - name: Publications
              url: /publications/
            - name: Courses
              url: /courses/
    socialIcons:
        - name: Email
          url: mailto:m.goos@uu.nl
        - name: CV
          url: /CV_Goos_202408.pdf
        - name: LinkedIn
          url: https://www.linkedin.com/in/maartengoos13/
        - name: Substack 
          url:  https://maartengoos.substack.com/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=7V39ONYAAAAJ
        - name: Location 
          url: /location/  
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Maarten Goos"
      icon: /picture.jpg
      iconHeight: 30
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
