baseURL: "https://maartengoos.com" 
title: Maarten Goos
paginate: 20
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
social:
    twitter: maarten_goos
taxonomies:
    tag: tags
menu:
    main:
        - name: Working papers
          url: /research/
          weight: 1
        - name: Teaching
          url: /teaching/
          weight: 2
        - name: Say more
          url: /more/
          weight: 3        
params:
    description: "homepage of Maarten Goos"
    author: Maarten Goos
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Maarten Goos
          subtitle: "I am an Institute Gak Endowed Professor at Utrecht University. My research focusses on labor problems, technological change, what unions do, monopsony, and inequality. For access to my published papers, click on my CV below."
          imageUrl: "/picture.jpg"
          imageWidth: 320
          imageHeight: 320
          imageTitle: Maarten Goos
          buttons:
            - name: Working papers
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: Say more
              url: /more/
    socialIcons:
        - name: CV
          url: /CV_Goos_202405.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=7V39ONYAAAAJ
        - name: Email
          url: mailto:m.goos@uu.nl
        - name: Location
          url: /location/
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Maarten Goos"
      icon: /picture.jpg
      iconHeight: 30
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
