baseURL: "https://maartengoos.com" 
title: Maarten Goos
paginate: 20
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
social:
    twitter: maarten_goos
taxonomies:
    tag: tags
menu:
    main:
        - name: working papers
          url: /research/
          weight: 1
        - name: publications
          url: /publications/
          weight: 2
        - name: teaching
          url: /teaching/
          weight: 3
        - name: say more
          url: /more/
          weight: 4        
params:
    description: "homepage of Maarten Goos"
    author: Maarten Goos
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Maarten Goos
          subtitle: "I am a labor economist. 
          In the first half of the 20th century, the Industrial Revolution served as a catalyst for growth and reduced inequality through the emergence of a middle class and democratic institutions such as education and trade unions. 
          However, since 1980, the middle class has eroded, downward mobility in the labor market has increased, the influence of trade unions has declined, and inequality has risen.
          Therefore, my research and teaching focus on labor problems, technological change, what unions do, monopsony, and inequality."
          imageUrl: "/picture.jpg"
          imageWidth: 320
          imageHeight: 320
          imageTitle: Maarten Goos
          buttons:
            - name: working papers
              url: /research/
            - name: publications
              url: /publications/
            - name: teaching
              url: /teaching/
            - name: say more
              url: /more/ 
    socialIcons:
        - name: CV
          url: /CV_Goos_202405.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=7V39ONYAAAAJ
        - name: LinkedIn
          url: https://www.linkedin.com/in/maartengoos13/
        - name: Location 
          url: /location/
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Maarten Goos"
      icon: /picture.jpg
      iconHeight: 30
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
